workflows:
  android-debug:
    name: Android Debug Build
    instance_type: mac_mini_m1
    environment:
      node: 18
      java: 21
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Set executable permissions
        script: chmod +x android/gradlew
      - name: Build Android APK
        script: |
          cd android
          ./gradlew clean assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
